// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqohqdbfwozavbcitjcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxb2hxZGJmd296YXZiY2l0amNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDcyMjUsImV4cCI6MjA1MzY4MzIyNX0.yUUjZMxLqsfFSVwXKcSJ0nxU53O_d8fd5pODZH2PiLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);